In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [8]:
my_Twodimen=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_Twodimen

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_Twodimen)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#numpy bult in arrays step=even/odd no of arrays
import numpy as np
np.arange(0,11,5)

array([ 0,  5, 10])

In [18]:
#creating arrays of zeros for one dimensional arrays
np.zeros(3)

array([0., 0., 0.])

In [21]:
#creating arrays of zeros for two dimensional arrays
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
#creating arrays of ones for two dimensional arrays
np.ones(3)

array([1., 1., 1.])

In [24]:
#creating arrays of ones for two dimensional arrays
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
#linspace start stop evebly spaced point from start to finish
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [29]:
#identity matrix --algeberia or unit diagonal matrices:
#it only take a digit as argument (4)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
#np.random.rand(5)

In [4]:
  np.random.rand(5,5)

array([[0.37394071, 0.27818102, 0.35284114, 0.90197648, 0.54204694],
       [0.2027832 , 0.55987064, 0.22351151, 0.68914009, 0.93971092],
       [0.16068683, 0.15087309, 0.8305684 , 0.64145707, 0.18166802],
       [0.83225504, 0.78477488, 0.90102277, 0.33921811, 0.8646839 ],
       [0.1969428 , 0.49307691, 0.73595641, 0.89728082, 0.61353938]])

In [5]:
np.random.randn(4,4)

array([[ 0.91411645, -0.13726329,  0.65499304,  2.1427048 ],
       [-1.20277017, -0.19933109,  0.34855483, -0.56199775],
       [-0.71135354, -1.08334908, -1.26371904, -1.07852662],
       [ 0.65573974,  0.72864868, -1.68222068,  1.25263351]])

In [82]:
np.random.randint(1,30,10)

array([ 6, 18, 27, 24,  2,  4,  6, 28, 17,  7])

In [58]:
arr=np.arange(50)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [66]:
ranarr=np.random.randint(0,100,10)

In [67]:
ranarr

array([78, 65, 58, 51, 74, 22, 82, 26, 22, 66])

In [60]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:
#mean
ranarr

array([78, 65, 58, 51, 74, 22, 82, 26, 22, 66])

In [69]:
ranarr.max()

82

In [70]:
ranarr.min()

22

In [71]:
#the index value(position) of max value
ranarr.argmax()

6

In [72]:
#the index value(position) of min value
ranarr.argmin()

5

In [73]:
#shape of the vector : arr is a one dimensional vector
arr.shape

(50,)

In [76]:
#2 dimensional arr
arr=arr.reshape(5,10)

In [78]:
arr.shape

(5, 10)

In [79]:
arr.dtype

dtype('int32')

In [80]:
from numpy.random import randint

In [81]:
randint(2,20)

16

In [83]:
#indexing and selection
import numpy as np

In [84]:
arr=np.arange(0,11)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr[8]

8

In [88]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [89]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [90]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [91]:
#broadcast
arr[0:5]=100

In [92]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [94]:
arr=np.arange(0,11)

In [104]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [96]:
slice_arr=arr[0:6]

In [97]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [99]:
slice_arr[:]=99

In [100]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [101]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [102]:
arr_copy=arr.copy()

In [103]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [105]:
arr_copy[:]=100

In [106]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [107]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])